{
 "title": "WQ-API",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(withdrawals_api_job_duration_seconds_count, exported_job)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(build_info{name=~\"$app_name\", env=~\"$env\"},source)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(build_info{name=~\"$app_name\"}, env)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(build_info{name=~\"$app_name\", env=~\"$env\", source=~\"$source\"},instance)"
    }
   },
   { "name": "container_name", "query": ".*withdrawals-api.*" },
   { "name": "app_name", "query": "withdrawals-api" },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(withdrawals_api_http_requests_duration_seconds_count, route)"
    }
   },
   {
    "name": "routeWithSource",
    "label": "Route with Source",
    "query": {
     "query": "label_values(withdrawals_api_requests_source,route)"
    }
   },
   {
    "name": "loglevel",
    "label": "Log Level",
    "query": "debug, info, warn, error, fatal"
   },
   { "name": "search", "label": "Search Logs" },
   { "name": "interval", "label": "interval", "query": "15s,1m,10m,30m,1h" },
   {
    "name": "service",
    "label": "service",
    "query": "rewards, validators, queue info, contract config"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Release details",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{name=\"$app_name\", env=~\"$env\", source=~\"$source\"}",
     "legendFormat": "ver: {{version}}"
    },
    {
     "expr": "build_info{name=\"$app_name\", env=~\"$env\", source=~\"$source\"}",
     "legendFormat": "network: {{network}}"
    },
    {
     "expr": "build_info{name=\"$app_name\", env=~\"$env\", source=~\"$source\"}",
     "legendFormat": "env: {{env}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - withdrawals_api_process_start_time_seconds{env=~\"$env\", source=~\"$source\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "All API request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (route)(increase(withdrawals_api_http_requests_duration_seconds_count{env=~\"$env\", route=~\"$route\"}[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "All API timings",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (le)(delta(withdrawals_api_http_requests_duration_seconds_bucket{env=~\"$env\", route=~\"$route\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors in logs count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"$env\", source=~\"$source\", container_name=~\".*$container_name.*\"} | json | __error__ != \"JSONParserErr\" | level = \"error\" or level = \"critical\" [1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Environment variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Environment variables",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "withdrawals_api_envs_info{env=~\"$env\",source=~\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API request count (by HTTP status)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$route",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (statusCode) (increase(withdrawals_api_http_requests_duration_seconds_count{env=~\"$env\", route=~\"$route\"}[1m]))",
       "legendFormat": "{{statusCode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API request timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$route",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "repeat": "route",
     "targets": [
      {
       "expr": "sum(increase(withdrawals_api_http_requests_duration_seconds_bucket{env=~\"$env\", route=~\"$route\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API request count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per routes ($route)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route)(increase(withdrawals_api_http_requests_duration_seconds_count{env=~\"$env\", route=~\"$route\",statusCode!~\"(4|5)..\"}[1m]))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Errors per routes ($route)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route)(increase(withdrawals_api_http_requests_duration_seconds_count{env=~\"$env\", route=~\"$route\",statusCode=~\"(4|5)..\"}[1m]))",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Source Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeWithSource",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "repeat": "routeWithSource",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (requestSource) (increase(withdrawals_api_requests_source{env=~\"$env\", route=~\"$routeWithSource\"}[1m]))",
       "legendFormat": "{{requestSource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job queue info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_job)(increase(withdrawals_api_job_duration_seconds_count{env=~\"$env\", source=~\"$source\", exported_job=\"update queue info\", result=\"success\"}[$__rate_interval]))",
       "legendFormat": "{{exported_job}}"
      }
     ]
    },
    {
     "title": "Job validators",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_job)(increase(withdrawals_api_job_duration_seconds_count{env=~\"$env\", exported_job=\"update validators\"}[5m]))",
       "legendFormat": "{{exported_job}}"
      }
     ]
    },
    {
     "title": "Job lido withdrawable validators",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exported_job)(increase(withdrawals_api_job_duration_seconds_count{env=~\"$env\", exported_job=\"update lido withdrawable validators\"}[$__rate_interval]))",
       "legendFormat": "{{exported_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result)(increase(withdrawals_api_el_rpc_requests_duration_seconds_count{env=~\"$env\"}[1m]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Timing",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "sum(increase(withdrawals_api_el_rpc_requests_duration_seconds_bucket{env=~\"$env\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result)(increase(withdrawals_api_cl_api_requests_duration_seconds_count{env=~\"$env\",status!~\"(4|5)..\"}[1m]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Timing",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "sum(increase(withdrawals_api_cl_api_requests_duration_seconds_bucket{env=~\"$env\"}[1d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "App Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "{env=~\"$env\", source=~\"$source\", container_name=~\".*$container_name.*\"} | json | __error__ != \"JSONParserErr\" | level=~\"$loglevel\" | line_format \"{{.name}}[{{.level}}]: {{.message}} {{.msg}} {{.context_originalUrl}}\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Logs (can't parse)",
     "type": "logs",
     "description": "Logs, which can't be parsed with JSON",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "{env=~\"$env\", source=~\"$source\", container_name=\"$container_name\"} | json | __error__ = \"JSONParserErr\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Logs by service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "repeat": "service",
     "targets": [
      {
       "expr": "{env=~\"$env\", source=~\"$source\", container_name=~\".*$container_name.*\"} | json | __error__ != \"JSONParserErr\" | context_service=~\"$service\" | level=~\"$loglevel\" | line_format \"{{.name}}[{{.level}}]: {{.message}} {{.msg}}\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Balances for calculation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Balances",
     "type": "timeseries",
     "description": "`buffer` - from contractWithdrawal.unfinalizedStETH\n\n`vaults` - sum of withdrawalVault and elRewardsVault\n\n`validators` -sum of all upcoming ETH from exiting validators\n\n`unfinalized` - sum of all withdrawal requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "withdrawals_api_balances_state_buffer{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "buffer"
      },
      {
       "expr": "withdrawals_api_balances_state_vaults{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "vaults"
      },
      {
       "expr": "withdrawals_api_balances_state_unfinalized{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "unfinalized"
      },
      {
       "expr": "withdrawals_api_sum_validators_balances{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "validators"
      }
     ]
    }
   ]
  },
  {
   "title": "Finalization statistics by report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Withdrawals by report from metrics (first calculated from event WithdrawalRequested)",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "count by (reportId) ((min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 3600000) and (min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 0))",
       "legendFormat": "Perfect"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 3600000 and min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) <= 172800000)",
       "legendFormat": "Good"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at))",
       "legendFormat": "Total"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 0)",
       "legendFormat": "Error"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_first_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) > 172800000)",
       "legendFormat": "Acceptable"
      }
     ]
    },
    {
     "title": "Withdrawals by report from metrics  (min from intermediate calculations)",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "count by (reportId) ((min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 3600000) and (min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 0))",
       "legendFormat": "Perfect"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 3600000 and min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) <= 172800000)",
       "legendFormat": "Good"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at))",
       "legendFormat": "Total"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 0)",
       "legendFormat": "Error"
      },
      {
       "expr": "count by (reportId) (min by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) > 172800000)",
       "legendFormat": "Acceptable"
      }
     ]
    },
    {
     "title": "Withdrawals by report from metrics (max from intermediate calculations)",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "count by (reportId) ((max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 3600000) and (max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 0))",
       "legendFormat": "Perfect"
      },
      {
       "expr": "count by (reportId) (max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) >= 3600000 and max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) <= 172800000)",
       "legendFormat": "Good"
      },
      {
       "expr": "count by (reportId) (max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at))",
       "legendFormat": "Total"
      },
      {
       "expr": "count by (reportId) (max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) < 0)",
       "legendFormat": "Error"
      },
      {
       "expr": "count by (reportId) (max by (requestId, reportId) (withdrawals_api_intermediate_request_finalization_at - on(requestId) group_left(reportId) withdrawals_api_request_finalized_at) > 172800000)",
       "legendFormat": "Acceptable"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{env=~\"$env\", source=~\"$source\", name=~\"$container_name\"}[1m])) * 100",
       "legendFormat": "user"
      },
      {
       "expr": "sum(rate(container_cpu_system_seconds_total{env=~\"$env\", source=~\"$source\", name=~\"$container_name\"}[1m])) * 100",
       "legendFormat": "system"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(withdrawals_api_process_resident_memory_bytes{env=~\"$env\", source=~\"$source\"})",
       "legendFormat": "resident"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration (major)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "rate(withdrawals_api_nodejs_gc_duration_seconds_bucket{env=~\"$env\", source=~\"$source\", kind=\"major\"}[1m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GC duration (minor)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "rate(withdrawals_api_nodejs_gc_duration_seconds_bucket{env=~\"$env\", source=~\"$source\",kind=\"minor\"}[1m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GC duration (incremental)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "rate(withdrawals_api_nodejs_gc_duration_seconds_bucket{env=~\"$env\", source=~\"$source\", kind=\"incremental\"}[1m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heap space size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "withdrawals_api_nodejs_heap_space_size_used_bytes{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "{{space}}"
      },
      {
       "expr": "sum(withdrawals_api_nodejs_heap_space_size_total_bytes{env=~\"$env\", source=~\"$source\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "External memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "withdrawals_api_nodejs_external_memory_bytes{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Heap size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "withdrawals_api_nodejs_heap_size_used_bytes{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "used"
      },
      {
       "expr": "withdrawals_api_nodejs_heap_size_total_bytes{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Active requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "withdrawals_api_nodejs_active_requests{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Active handles (by type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "withdrawals_api_nodejs_active_handles{env=~\"$env\", source=~\"$source\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Eventloop lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_min_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "min"
      },
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_mean_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "mean"
      },
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_max_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Eventloop lag (percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_p50_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "p50"
      },
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_p90_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "p90"
      },
      {
       "expr": "rate(withdrawals_api_nodejs_eventloop_lag_p99_seconds{env=~\"$env\", source=~\"$source\"}[1m])",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}