name: CI Dev Hoodi

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - ".github/**"

permissions:
  contents: read
  

jobs:
  tests:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    name: Build and deploy
    steps:
      - name: Hoodi testnet deploy
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TARGET_WORKFLOW: "deploy_hoodi_testnet_withdrawals_api.yaml"
          TARGET: "develop"
