name: CI Build prod image

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  tests:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    name: Build and deploy
    steps:
      - name: Build prod image
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TAG: "${{ github.event.release.tag_name }}"
          TARGET_WORKFLOW: "build_mainnet_withdrawals_api.yaml"