name: Tests

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile
    
      - name: Run tests
        run: yarn test
    
